services:

  distributedcache:
    image: redis:7.4.1
    container_name: distributedcache
    ports:
      - "6379:6379"
    volumes:
      - redis_distributedcache:/data

  catalogdb:
    container_name: catalog.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catalog
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data

  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: src/services/Catalog/Dockerfile
      args:
        configuration: Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ConnectionStrings__Database=Host=catalogdb;Port=5432;Database=catalog;Username=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - catalogdb
    ports:
      - "5000:8080"
      - "5001:8081"
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ./src/services/Catalog:/app
      - /Users/jose.padilla/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - /Users/jose.padilla/ASP.NET/Https:/app/https:ro

  basketdb:
    container_name: basket.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=basket
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data

  basketapi:
    image: basketapi
    build:
      context: .
      dockerfile: src/services/Basket/Dockerfile
      args:
        configuration: Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - GrpcSettings__DiscountUrl=https://discountgrpc:8081
      - ConnectionStrings__Database=Host=basketdb;Port=5432;Database=basket;Username=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__Redis=distributedcache:6379
    depends_on:
      - basketdb
      - distributedcache
    ports:
      - "5002:8080"
      - "5003:8081"
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ./src/services/Basket:/app
      - /Users/jose.padilla/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - /Users/jose.padilla/ASP.NET/Https:/app/https:ro

  discountgrpc:
    image: discountgrpc
    build:
      context: .
      dockerfile: src/services/DiscountGrpc/Dockerfile
      args:
        configuration: Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ConnectionStrings__Database=Data Source=discount.sqlite
    ports:
      - "5004:8080"
      - "5005:8081"
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ./src/services/DiscountGrpc:/app
      - /Users/jose.padilla/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - /Users/jose.padilla/ASP.NET/Https:/app/https:ro

  orderdb:
    container_name: order.db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123@!
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - /Users/jose.padilla/Microsoft:/var/opt/mssql

volumes:
  redis_distributedcache:
  postgres_catalog:
  postgres_basket:
