services:
  distributedcache:
    image: redis:7.4.1

  catalog.db:
    image: postgres:17
  catalog.api:
    image: catalog.api
    build:
      context: ../
      dockerfile: src/services/Catalog/Dockerfile
  
  basket.db:
    image: postgres:17

volumes:
  postgres_catalog:
  postgres_basket:
  redis_distributedcache: