services:
  distributedcache:
    image: redis:7.4.1
    container_name: distributedcache
    ports:
      - "6379:6379"
    volumes:
      - redis_distributedcache:/data

  catalog.db:
    container_name: catalog.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catalog
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_HTTP_PORT=8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/https/aspnetapp.pfx
      - ASPNETCORE_URLS=https://+:${ASPNETCORE_HTTPS_PORT:-8081};http://+:${ASPNETCORE_HTTP_PORT:-8080}
      - ConnectionStrings__Database=Host=catalog.db;Port=5432;Database=catalog;Username=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - catalog.db
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - /Users/jose.padilla/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - /Users/jose.padilla/ASP.NET/Https:/app/https:ro
  
  basket.db:
    container_name: basket.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=basket
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_HTTP_PORT=8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/https/aspnetapp.pfx
      - ASPNETCORE_URLS=https://+:${ASPNETCORE_HTTPS_PORT:-8081};http://+:${ASPNETCORE_HTTP_PORT:-8080}
      - GrpcSettings__DiscountUrl=https://discount.grpc:8081
      - ConnectionStrings__Database=Host=basket.db;Port=5432;Database=basket;Username=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__Redis=distributedcache:6379
    depends_on:
      - basket.db
      - distributedcache
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - /Users/jose.padilla/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - /Users/jose.padilla/ASP.NET/Https:/app/https:ro
  
  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_HTTP_PORT=8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/https/aspnetapp.pfx
      - ASPNETCORE_URLS=https://+:${ASPNETCORE_HTTPS_PORT:-8081};http://+:${ASPNETCORE_HTTP_PORT:-8080}
      - ConnectionStrings__Database=Data Source=discount.sqlite
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - /Users/jose.padilla/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - /Users/jose.padilla/ASP.NET/Https:/app/https:ro
  
  order.db:
    container_name: order.db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123@!
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - /Users/jose.padilla/Microsoft:/var/opt/mssql
    
  order.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_HTTP_PORT=8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/https/aspnetapp.pfx
      - ASPNETCORE_URLS=https://+:${ASPNETCORE_HTTPS_PORT:-8081};http://+:${ASPNETCORE_HTTP_PORT:-8080}
      - ConnectionStrings__Database=Server=order.db;Database=order;User Id=sa;Password=Password123@!;Encrypt=False;TrustServerCertificate=True
    depends_on:
      - order.db
    ports:
      - "6003:8080"
      - "6063:8081"
    volumes:
      - /Users/jose.padilla/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - /Users/jose.padilla/ASP.NET/Https:/app/https:ro

volumes:
  redis_distributedcache:
  postgres_catalog:
  postgres_basket: