services:
  distributedcache:
    image: redis:7.4.1

  catalog.db:
    image: postgres:17
  catalog.api:
    image: catalog.api
    build:
      context: ../
      dockerfile: src/services/Catalog/Dockerfile
  
  basket.db:
    image: postgres:17
  basket.api:
    image: basket.api
    build:
      context: ../
      dockerfile: src/services/Basket/Dockerfile

  discount.grpc:
    image: discount.grpc
    build:
      context: ../
      dockerfile: src/services/Discount/Dockerfile
  
  order.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
  order.api:
    image: order.api
    build:
      context: ../
      dockerfile: src/services/Ordering/Ordering.API/Dockerfile
  
  messagebroker:
    image: rabbitmq:4.0.3-management

volumes:
  postgres_catalog:
  postgres_basket: